/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2022-07-20 13:07:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gugi&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"fontawesome/css/all.min.css\">\r\n");
      out.write("<!-- https://fontawesome.com/ -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/templatemo-ocean-vibes.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/nav.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/c34800a0df.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- 서머노트링크 -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.js\"></script>\r\n");
      out.write("<!-- /서머노트링크 -->\r\n");
      out.write("<style>\r\n");
      out.write("@font-face {\r\n");
      out.write("   font-family: 'yg-jalnan';\r\n");
      out.write("   src:\r\n");
      out.write("      url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.2/JalnanOTF00.woff')\r\n");
      out.write("      format('woff');\r\n");
      out.write("   font-weight: normal;\r\n");
      out.write("   font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@import url(\"https://fonts.googleapis.com/css?family=Inconsolata:700\");\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   box-sizing: border-box;\r\n");
      out.write("   font-family: 'yg-jalnan', cursive\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body {\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   top: 0;\r\n");
      out.write("   left: 0;\r\n");
      out.write("   right: 50px;\r\n");
      out.write("   bottom: 0;\r\n");
      out.write("   width: 200px;\r\n");
      out.write("   height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container .search {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   top: 0;\r\n");
      out.write("   right: 0;\r\n");
      out.write("   bottom: 0;\r\n");
      out.write("   left: 0;\r\n");
      out.write("   width: 40px;\r\n");
      out.write("   height: 40px;\r\n");
      out.write("   background: #98a6c3;\r\n");
      out.write("   border-radius: 50%;\r\n");
      out.write("   transition: all 0.5s;\r\n");
      out.write("   z-index: 4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container .search:hover {\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container .search::before {\r\n");
      out.write("   content: \"\";\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   top: 22px;\r\n");
      out.write("   right: 0;\r\n");
      out.write("   bottom: 0;\r\n");
      out.write("   left: 22px;\r\n");
      out.write("   width: 12px;\r\n");
      out.write("   height: 2px;\r\n");
      out.write("   background: white;\r\n");
      out.write("   transform: rotate(45deg);\r\n");
      out.write("   transition: all 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container .search::after {\r\n");
      out.write("   content: \"\";\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   top: -5px;\r\n");
      out.write("   right: 0;\r\n");
      out.write("   bottom: 0;\r\n");
      out.write("   left: -5px;\r\n");
      out.write("   width: 25px;\r\n");
      out.write("   height: 25px;\r\n");
      out.write("   border-radius: 50%;\r\n");
      out.write("   border: 2px solid white;\r\n");
      out.write("   transition: all 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container input {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   top: 0;\r\n");
      out.write("   right: 0;\r\n");
      out.write("   bottom: 0;\r\n");
      out.write("   left: 0;\r\n");
      out.write("   width: 50px;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("   outline: none;\r\n");
      out.write("   border: none;\r\n");
      out.write("   color: black;\r\n");
      out.write("   padding: 0 80px 0 20px;\r\n");
      out.write("   border-radius: 30px;\r\n");
      out.write("   box-shadow: 0 0 25px 0 #98b2cd, 0 20px 25px 0 rgba(0, 0, 0, 0.2);\r\n");
      out.write("   transition: all 0.5s;\r\n");
      out.write("   opacity: 0;\r\n");
      out.write("   z-index: 5;\r\n");
      out.write("   font-weight: bolder;\r\n");
      out.write("   letter-spacing: 0.1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container input:hover {\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container input:focus {\r\n");
      out.write("   width: 200px;\r\n");
      out.write("   opacity: 1;\r\n");
      out.write("   cursor: text;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container input:focus ~ .search {\r\n");
      out.write("   right: -150px;\r\n");
      out.write("   background: #98a6c3;\r\n");
      out.write("   z-index: 6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container input:focus ~ .search::before {\r\n");
      out.write("   top: 0;\r\n");
      out.write("   left: 0;\r\n");
      out.write("   width: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container input:focus ~ .search::after {\r\n");
      out.write("   top: 0;\r\n");
      out.write("   left: 0;\r\n");
      out.write("   width: 25px;\r\n");
      out.write("   height: 2px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   background: white;\r\n");
      out.write("   border-radius: 0%;\r\n");
      out.write("   transform: rotate(-45deg);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_container input::placeholder {\r\n");
      out.write("   color: white;\r\n");
      out.write("   opacity: 0.5;\r\n");
      out.write("   font-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("   <nav class=\"navbar\">\r\n");
      out.write("      <div class=\"navbar_logo\">\r\n");
      out.write("         <i class=\"fa-solid fa-map-location-dot\"></i> <a href=\"home.jsp\">여행가기\r\n");
      out.write("            좋은날</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"head_container\">\r\n");
      out.write("         <form action=\"home.jsp\">\r\n");
      out.write("            <input type=\"text\" name=\"search\" placeholder=\"Search...\">\r\n");
      out.write("               <div class=\"search\">\r\n");
      out.write("               </div>\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <ul class=\"navbar_menu\">\r\n");
      out.write("         <li><a href=\"destination.jsp\">여행지 추천</a></li>\r\n");
      out.write("         <li><a href=\"course/page.do\">코스 추천</a></li>\r\n");
      out.write("         <li><a href=\"festival.jsp\">축제</a></li>\r\n");
      out.write("         <li><a href=\"board.jsp\">자유게시판</a></li>\r\n");
      out.write("         <li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("   </nav>\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
