/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2022-08-05 05:59:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>여행가기 좋은날</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://kit.fontawesome.com/c34800a0df.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("<style>\n");
      out.write("    @font-face {\n");
      out.write("    font-family: 'yg-jalnan';\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.2/JalnanOTF00.woff') format('woff');\n");
      out.write("    font-weight: normal;\n");
      out.write("    font-style: normal;\n");
      out.write("}\n");
      out.write("      \n");
      out.write("   * {font-family: 'yg-jalnan', cursive }\n");
      out.write("\n");
      out.write(" ul > li > a {color: #212121;}\n");
      out.write(" \n");
      out.write(".bg:hover {\n");
      out.write("  opacity:0.7;\n");
      out.write(" }\n");
      out.write(".carousel-inner{\n");
      out.write("   // height: 300px;\n");
      out.write("}\n");
      out.write("p {color : #212121;}\n");
      out.write(".item, img{\n");
      out.write("    height: 500px; !important;\n");
      out.write("    width:  100% !important;\n");
      out.write("    \n");
      out.write("</style>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"card\">\n");
      out.write("   \n");
      out.write("</div>\n");
      out.write("<br><br>\n");
      out.write("   <a style=\"display:scroll;position:fixed;bottom:20px;z-index: 999;right:60px;font-size: 40px;\" href=\"#\" title=”top\">\n");
      out.write("   <i class=\"fa-solid fa-circle-arrow-up\"></i></a>\n");
      out.write("   <!-- header card -->\n");
      out.write("   \n");
      out.write("   <!-- header card -->\n");
      out.write("   \n");
      out.write("   <div class=\"card\">\n");
      out.write("   \n");
      out.write("   </div>\n");
      out.write("   \n");
      out.write("\n");
      out.write("<div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("    <ol class=\"carousel-indicators\">\n");
      out.write("        <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("        <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\n");
      out.write("        <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\n");
      out.write("    </ol>\n");
      out.write("    <div class=\"carousel-inner\">\n");
      out.write("        <div class=\"carousel-item active\">\n");
      out.write("            <img class=\"carousel-img d-block w-100\" src=\"/resources/img/jejudo.jpg\" alt=\"First slide\">\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                <p class=\"subtitle\"> <h1>올 여름, 해수욕장 어디로 가지?</h1></p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"carousel-item\">\n");
      out.write("            <img class=\"carousel-img d-block w-100\" src=\"/resources/img/BlueHouse.jpg\" alt=\"Second slide\">\n");
      out.write("             <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                <p class=\"subtitle\"><h1>74년 만에 공개된 비밀 정원, 청와대 이야기</h1></p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"carousel-item\">\n");
      out.write("            <img class=\"carousel-img d-block w-100\" src=\"/resources/img/Woljeonggyo.jpg\" alt=\"Third slide\">\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                <p class=\"subtitle\"><h1>신라 천년의 밤을 만나다! 경주 동궁과 월지, 월정교</h1></p>\n");
      out.write("            </div>\n");
      out.write("        \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!-- Control Btn -->\n");
      out.write("    \n");
      out.write("    <a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">\n");
      out.write("        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("        <span class=\"sr-only\">Previous</span>\n");
      out.write("    </a>\n");
      out.write("    <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\">\n");
      out.write("        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("        <span class=\"sr-only\">Next</span>\n");
      out.write("    </a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   \n");
      out.write("   \n");
      out.write("   \n");
      out.write("         \n");
      out.write("   <br><br><br>\n");
      out.write("   <div class=\"container\">\n");
      out.write("   <div class=\"text-center\">\n");
      out.write("               <h2>함께 떠나는 힐링 테마여행</h2>\n");
      out.write("               <p> 설명?</p>\n");
      out.write("            </div>\n");
      out.write("   <div class=\"row g-1\">\n");
      out.write("            <div class=\"col-4\">\n");
      out.write("               <a href=\"images/img_1.jpg\" class=\"fh5co-card-item image-popup\">\n");
      out.write("                  <figure>\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\n");
      out.write("                     <img src=\"/resources/img/seosan.jpg\" alt=\"Image\" class=\"img-responsive\">\n");
      out.write("                  </figure>\n");
      out.write("                  <div class=\"fh5co-text\">\n");
      out.write("                     <h2>충청도</h2>\n");
      out.write("                     <p>역사와 자연이 조화로운 서산 여행</p>\n");
      out.write("                     <p><span class=\"btn btn-primary\"> 보러가기</span></p>\n");
      out.write("                  </div>\n");
      out.write("               </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-4\">\n");
      out.write("               <a href=\"/resources/images/img_2.jpg\" class=\"fh5co-card-item image-popup\">\n");
      out.write("                  <figure>\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\n");
      out.write("                     <img src=\"/resources/img/yeongwol.jpg\" alt=\"Image\" class=\"img-responsive\">\n");
      out.write("                  </figure>\n");
      out.write("                  <div class=\"fh5co-text\">\n");
      out.write("                     <h2>강원도 </h2>\n");
      out.write("                     <p>영월로 떠나는 어느 여름날의 강원도 힐링여행</p>\n");
      out.write("                     <p><span class=\"btn btn-primary\">보러가기</span></p>\n");
      out.write("                  </div>\n");
      out.write("               </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-4\">\n");
      out.write("               <a href=\"/resources/images/img_3.jpg\" class=\"fh5co-card-item image-popup\">\n");
      out.write("                  <figure>\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\n");
      out.write("                     <img src=\"/resources/img/pet.jpg\"\" alt=\"Image\" class=\"img-responsive\">\n");
      out.write("                  </figure>\n");
      out.write("                  <div class=\"fh5co-text\">\n");
      out.write("                     <h2>경상도</h2>\n");
      out.write("                     <p>반려견과의 특별한 하루를, 의성펫월드</p>\n");
      out.write("                     <p><span class=\"btn btn-primary\">보러가기</span></p>\n");
      out.write("                  </div>\n");
      out.write("               </a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"col-4\">\n");
      out.write("               <a href=\"/resources/images/img_4.jpg\" class=\"fh5co-card-item image-popup\">\n");
      out.write("                  <figure>\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\n");
      out.write("                     <img src=\"/resources/img/suwon.jpeg\" alt=\"Image\" class=\"img-responsive\">\n");
      out.write("                  </figure>\n");
      out.write("                  <div class=\"fh5co-text\">\n");
      out.write("                     <h2>경기도</h2>\n");
      out.write("                     <p>하루만에 즐기는 수원 당일치기 여행코스</p>\n");
      out.write("                     <p><span class=\"btn btn-primary\">보러가기</span></p>\n");
      out.write("                  </div>\n");
      out.write("               </a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-4\">\n");
      out.write("               <a href=\"/resources/images/img_5.jpg\" class=\"fh5co-card-item image-popup\">\n");
      out.write("                  <figure>\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\n");
      out.write("                     <img src=\"/resources/img/yeosu.jpg\" alt=\"Image\" class=\"img-responsive\">\n");
      out.write("                  </figure>\n");
      out.write("                  <div class=\"fh5co-text\">\n");
      out.write("                     <h2>전라도</h2>\n");
      out.write("                     <p>잠들지 않는 낭만의 도시, 여수를 만끽하다 </p>\n");
      out.write("                     <p><span class=\"btn btn-primary\">보러가기</span></p>\n");
      out.write("                  </div>\n");
      out.write("               </a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-sm-4\">\n");
      out.write("               <a href=\"/resources/images/img_6.jpg\" class=\"fh5co-card-item image-popup\">\n");
      out.write("                  <figure>\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\n");
      out.write("                     <img src=\"/resources/img/jeju.jpeg\" alt=\"Image\" class=\"img-responsive\">\n");
      out.write("                  </figure>\n");
      out.write("                  <div class=\"fh5co-text\">\n");
      out.write("                     <h2>제주도</h2>\n");
      out.write("                     <p>섬 안에 섬을 여행하는 방법, 가파도 여행 코스</p>\n");
      out.write("                     <p><span class=\"btn btn-primary\">보러가기</span></p>\n");
      out.write("                  </div>\n");
      out.write("               </a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   \n");
      out.write("   <br><br><br>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>   \n");
      out.write("   ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
